# Model arguments
model_name_or_path: Qwen/Qwen3-0.6B
tokenizer_name_or_path: Qwen/Qwen3-0.6B
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager
use_liger: false
bf16: true
tf32: true
output_dir: /opt/ml/output/data/qwen3-06b

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/train/finance-instruct-500k.jsonl
max_seq_length: 4096
packing: true

# LoRA arguments
use_peft: true
load_in_4bit: false
lora_target_modules: "all-linear"
lora_modules_to_save: ["lm_head", "embed_tokens"]
lora_r: 16
lora_alpha: 16

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 1.0e-4 
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- mlflow
run_name: fine-tuning-run-1
save_strategy: "epoch"
seed: 42
